<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2015-08-08T15:24:33+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id      = 5;
	$section_id   = 12;
	$post_id      = 2;
	$post_section = 12;
	require('../../index.php');
// *************************************************
