<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2015-08-04T20:30:35+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 4;
	require('../index.php');
// *************************************************
