<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2015-06-21T17:41:59+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 4;
	require('../../index.php');
// *************************************************
